'use client';
import { useEffect, useState } from 'react';
import { emptyIndiaCollege, getIndiaAdminPages, IndiaCollegeData, IndiaPage } from '@/lib/india';
const input = 'mt-1 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-[#F26419]';
export function IndiaCollegeFields({ stateId, value, onChange }: { stateId: string; value?: IndiaCollegeData; onChange: (stateId: string, data: IndiaCollegeData) => void }) {
  const [states, setStates] = useState<IndiaPage[]>([]);
  const [error,setError] = useState('');
  const data = { ...emptyIndiaCollege(), ...value };
  useEffect(() => { getIndiaAdminPages().then(p => setStates(p.filter(s => s.kind === 'state'))).catch(() => setError('Could not load India states. Reload to try again.')); }, []);
  const update = (key: keyof IndiaCollegeData, value: unknown) => onChange(stateId, { ...data, [key]: value });
  return <section className="space-y-4 rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold text-gray-900">MBBS India — state & admission data</h2><p className="text-xs text-gray-500">Select India as the country, then assign a state. Leave the state empty for colleges outside India.</p>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<label className="block text-sm font-medium">State<select value={stateId} onChange={e => onChange(e.target.value,data)} className={input}><option value="">Not assigned</option>{states.map(s => <option key={s._id} value={s._id}>{s.name}{s.status === 'draft' ? ' (draft)' : ''}</option>)}</select></label>
    {stateId && <><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Management<select value={data.management} onChange={e => update('management',e.target.value)} className={input}><option value="">Not specified</option><option>Government</option><option>Private</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.deemed} onChange={e => update('deemed',e.target.checked)} />Deemed university</label>{(['annualTuition','seats'] as const).map(k => <label key={k} className="text-sm font-medium">{k === 'seats' ? 'Verified MBBS seats' : 'Annual tuition in INR'}<input type="number" min="0" step="1" value={data[k] ?? ''} onChange={e => update(k,e.target.value === '' ? null : Number(e.target.value))} className={input} /></label>)}{(['academicYear','verifiedAt','sourceUrl'] as const).map(k => <label key={k} className="text-sm font-medium">{{academicYear:'Academic year',verifiedAt:'Last reviewed',sourceUrl:'Official college/source URL'}[k]}<input type={k === 'verifiedAt' ? 'date' : k === 'sourceUrl' ? 'url' : 'text'} value={data[k]} onChange={e => update(k,e.target.value)} className={input} /></label>)}</div>{(['admission','otherFees'] as const).map(k => <label key={k} className="block text-sm font-medium">{k === 'admission' ? 'Admission & counselling information' : 'Other charges / refundable deposits (label each clearly)'}<textarea value={data[k]} onChange={e => update(k,e.target.value)} rows={4} className={input} /></label>)}<h3 className="font-medium">Previous cutoffs</h3>{data.cutoffs.map((r,i) => <div key={i} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-3">{(['year','category','quota','round','closingRank','sourceUrl'] as const).map(k => <label key={k} className="text-xs">{{year:'Year',category:'Category',quota:'Quota',round:'Round',closingRank:'Closing rank',sourceUrl:'Official source URL'}[k]}<input required type={k === 'year' || k === 'closingRank' ? 'number' : k === 'sourceUrl' ? 'url' : 'text'} min="1" value={r[k]} onChange={e => update('cutoffs',data.cutoffs.map((row,j) => j === i ? {...row,[k]: k === 'year' || k === 'closingRank' ? Number(e.target.value) : e.target.value} : row))} className={input} /></label>)}<button type="button" className="text-sm text-red-600" onClick={() => update('cutoffs',data.cutoffs.filter((_,j) => j !== i))}>Remove cutoff</button></div>)}<button type="button" className="text-sm font-semibold text-[#F26419]" onClick={() => update('cutoffs',[...data.cutoffs,{year:new Date().getFullYear()-1,category:'',quota:'',round:'',closingRank:1,sourceUrl:''}])}>+ Add cutoff row</button></>}
  </section>;
}
