import Link from 'next/link';
import { IndiaCollege, IndiaPage, httpUrl } from '@/lib/india';
import { stripHtml } from '@/lib/utils';
import { SafeImage } from '@/components/ui/SafeImage';
import { IndiaEnquiry } from './IndiaEnquiry';
export function IndiaCollegeView({ college: c, state }: { college: IndiaCollege; state?: IndiaPage }) {
  const d = c.india;
  const rows = [['Management', d.management], ['University status', d.deemed ? 'Deemed university' : ''], ['MBBS seats', d.seats != null ? String(d.seats) : ''], ['Annual tuition', d.annualTuition != null ? `₹${d.annualTuition.toLocaleString('en-IN')}` : 'Awaiting verified update'], ['Hostel fees', c.hostelFees], ['Academic year', d.academicYear], ['Last reviewed', d.verifiedAt]];
  return <div className="bg-[#F9F8F6]"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><nav aria-label="Breadcrumb" className="mb-7 text-sm"><Link href="/mbbs-india" className="text-[#F26419]">MBBS India</Link>{state && <> / <Link href={`/mbbs-india/${state.slug}`}>{state.name}</Link></>} / {c.name}</nav><div className="grid items-start gap-8 lg:grid-cols-[1.4fr_1fr]"><div><p className="font-semibold text-[#F26419]">{[c.city, state?.name].filter(Boolean).join(', ')}</p><h1 className="my-4 font-heading text-3xl font-bold text-[#0D1B3E] sm:text-4xl">{c.name}</h1>{c.heroImage && <SafeImage src={c.heroImage} alt={c.heroImageAlt || c.name} width={1000} height={600} className="my-6 w-full rounded-2xl object-cover" />}<p className="whitespace-pre-line leading-relaxed">{stripHtml(c.description || '')}</p><dl className="my-6 rounded-2xl border border-gray-200 bg-white p-6">{rows.filter(([,v]) => v).map(([k,v]) => <div key={k} className="flex justify-between gap-5 border-b border-gray-100 py-3 last:border-0"><dt>{k}</dt><dd className="text-right font-semibold text-[#0D1B3E]">{v}</dd></div>)}</dl>{[['Eligibility', c.eligibility], ['Admission & counselling', d.admission], ['Other fees & deposits', d.otherFees]].filter(([,v]) => v).map(([k,v]) => <section key={k} className="mb-5 rounded-2xl border border-gray-200 bg-white p-6"><h2 className="font-heading text-xl font-bold text-[#0D1B3E]">{k}</h2><p className="mt-3 whitespace-pre-line">{stripHtml(v || '')}</p></section>)}{httpUrl(d.sourceUrl) && <a href={d.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-[#F26419]">Official college information ↗</a>}</div><IndiaEnquiry state={state?.name} college={c.name} /></div>
    {d.cutoffs?.length > 0 && <section className="mt-10"><h2 className="mb-4 font-heading text-2xl font-bold text-[#0D1B3E]">Previous closing ranks</h2><div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#0D1B3E] text-white"><tr>{['Year','Category','Quota','Round','Closing rank','Source'].map(h => <th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{d.cutoffs.map((r,i) => <tr key={i} className="border-t border-gray-100">{[r.year,r.category,r.quota,r.round,r.closingRank].map((v,j) => <td key={j} className="p-4">{v}</td>)}<td className="p-4">{httpUrl(r.sourceUrl) && <a href={r.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-[#F26419]">Official source ↗</a>}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-gray-500">Historical closing ranks are for reference and do not guarantee admission.</p></section>}
    {!!c.faqs?.length && <section className="mt-10"><h2 className="mb-5 font-heading text-2xl font-bold text-[#0D1B3E]">Frequently asked questions</h2>{c.faqs.map((f,i) => <details key={i} className="mb-3 rounded-xl bg-white p-5"><summary className="cursor-pointer font-semibold">{f.question}</summary><p className="mt-3">{stripHtml(f.answer)}</p></details>)}</section>}</div></div>;
}
