import Link from 'next/link';
import { IndiaPage, IndiaCollege, httpUrl } from '@/lib/india';
import { SafeImage } from '@/components/ui/SafeImage';
import { IndiaEnquiry } from './IndiaEnquiry';
import { IndiaDirectory } from './IndiaDirectory';
export function IndiaPageView({ page, states = [], colleges = [], preview = false }: { page: IndiaPage; states?: IndiaPage[]; colleges?: IndiaCollege[]; preview?: boolean }) {
  const isState = page.kind === 'state';
  return <div className="bg-white text-[#4A4742]">
    <div className="border-b border-gray-100 bg-[#F9F8F6] px-4 py-3 text-xs"><nav aria-label="Breadcrumb" className="mx-auto max-w-7xl"><Link href="/">Home</Link><span className="mx-2">/</span>{isState ? <><Link href="/mbbs-india" className="text-[#F26419]">MBBS India</Link><span className="mx-2">/</span>{page.name}</> : 'MBBS India'}</nav></div>
    <section className="bg-gradient-to-br from-[#fff5ef] via-[#F9F8F6] to-[#edf3fa] py-10 sm:py-16"><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-[1.25fr_1fr] lg:px-8">
      <div><span className="inline-flex rounded-full border border-[#F26419]/20 bg-[#F26419]/5 px-4 py-2 text-xs font-bold uppercase tracking-widest text-[#F26419]">{isState ? `${page.name} · State guide` : 'Medical education · India'}</span><h1 className="mt-6 max-w-2xl font-heading text-4xl font-bold leading-tight text-[#0D1B3E] sm:text-5xl">{page.title || `MBBS in ${page.name}`}</h1><p className="mt-5 max-w-xl whitespace-pre-line text-base leading-relaxed text-gray-600">{page.intro}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#explore" className="rounded-full bg-[#F26419] px-6 py-3 text-sm font-bold text-white">{isState ? 'Explore colleges' : 'Explore states'} →</a><Link href="/college-predictor" className="rounded-full border border-[#0D1B3E] px-6 py-3 text-sm font-bold text-[#0D1B3E]">College predictor</Link></div>{page.verifiedAt && <p className="mt-6 text-xs text-gray-500">Last reviewed: {page.verifiedAt}{page.academicYear && ` · Academic year ${page.academicYear}`}</p>}</div>
      <IndiaEnquiry state={isState ? page.name : ''} states={states} label={page.ctaLabel} preview={preview} />
    </div></section>
    {page.highlights.length > 0 && <section className="bg-[#0D1B3E] py-8"><dl className="mx-auto grid max-w-7xl grid-cols-2 gap-4 px-4 sm:px-6 lg:grid-cols-4 lg:px-8">{page.highlights.map((h,i) => <div key={i} className="rounded-xl border border-white/10 bg-white/5 p-5"><dt className="text-xs uppercase tracking-wide text-white/65">{h.label}</dt><dd className="mt-2 font-heading text-xl font-bold text-white">{h.value}</dd></div>)}</dl></section>}
    <IndiaDirectory states={states} colleges={isState ? colleges : undefined} storageKey={`india-${page.slug}`} />
    {page.image && <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SafeImage src={page.image} alt={page.imageAlt || page.title} width={1280} height={520} className="max-h-96 w-full rounded-2xl object-cover" /></div>}
    <div className="mx-auto grid max-w-7xl gap-6 px-4 py-10 sm:px-6 lg:grid-cols-2 lg:px-8">{page.sections.filter(s => s.visible).map((s,i) => <section key={i} className="rounded-2xl border border-gray-200 bg-[#F9F8F6] p-6 sm:p-8"><p className="mb-3 text-xs font-bold tracking-widest text-[#F26419]">{String(i+1).padStart(2,'0')}</p><h2 className="font-heading text-2xl font-bold text-[#0D1B3E]">{s.title}</h2><p className="mt-4 whitespace-pre-line leading-relaxed">{s.body}</p></section>)}</div>
    {(page.authority || page.sources.length > 0) && <section className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 lg:px-8"><div className="rounded-2xl border border-gray-200 p-6"><h2 className="font-heading text-xl font-bold text-[#0D1B3E]">Official information & sources</h2>{page.authority && <p className="mt-3">{page.authority}</p>}<ul className="mt-3 space-y-2 text-sm text-[#F26419]">{httpUrl(page.officialUrl) && <li><a href={page.officialUrl} target="_blank" rel="noopener noreferrer">Official counselling website ↗</a></li>}{page.sources.filter(s => httpUrl(s.url)).map((s,i) => <li key={i}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.label || s.url} ↗</a></li>)}</ul></div></section>}
    {page.faqs.length > 0 && <section className="bg-[#F9F8F6] py-12"><div className="mx-auto max-w-3xl px-4"><h2 className="mb-6 font-heading text-3xl font-bold text-[#0D1B3E]">Your questions, answered</h2>{page.faqs.map((f,i) => <details key={i} className="mb-3 rounded-xl border border-gray-200 bg-white p-5"><summary className="cursor-pointer font-semibold text-[#0D1B3E]">{f.question}</summary><p className="mt-3 whitespace-pre-line text-sm leading-relaxed">{f.answer}</p></details>)}</div></section>}
    <section className="bg-[#0D1B3E] px-4 py-12 text-center text-white"><h2 className="font-heading text-3xl font-bold">Ready to explore your options?</h2><a href="#counselling" className="mt-6 inline-block rounded-full bg-[#F26419] px-7 py-3 font-bold">{page.ctaLabel || 'Get free counselling'} →</a></section>
  </div>;
}
