'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import AdminLayout from '@/components/admin/AdminLayout';
import ImageUploader from '@/components/admin/ImageUploader';
import { IndiaPageView } from '@/components/india/IndiaPageView';
import { IndiaPage, emptyIndiaPage, getIndiaAdminPages, indiaPath } from '@/lib/india';
import { adminApi } from '@/lib/api';
import { handleApiError } from '@/lib/handleApiError';
const input = 'mt-1 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-[#F26419]';
const button = 'rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-semibold text-[#0D1B3E] disabled:opacity-50';
function TextField({ label, value, onChange, multiline = false, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; type?: string; required?: boolean }) { return <label className="block text-sm font-medium text-gray-700">{label}{multiline ? <textarea required={required} value={value} onChange={e => onChange(e.target.value)} rows={4} className={input} /> : <input required={required} type={type} value={value} onChange={e => onChange(e.target.value)} className={input} />}</label>; }
function Rows<T extends object>({ title, rows, fields, blank, onChange }: { title: string; rows: T[]; fields: { key: keyof T; label: string; multiline?: boolean }[]; blank: T; onChange: (rows: T[]) => void }) {
  return <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="mb-4 font-semibold text-gray-900">{title}</h2><div className="space-y-4">{rows.map((row,i) => <div key={i} className="space-y-3 rounded-xl border border-gray-200 bg-gray-50 p-4">{fields.map(f => <TextField key={String(f.key)} label={f.label} value={String(row[f.key] ?? '')} multiline={f.multiline} onChange={value => onChange(rows.map((r,j) => i === j ? { ...r, [f.key]: value } : r))} />)}{'visible' in row && <label className="flex gap-2 text-sm"><input type="checkbox" checked={Boolean(row.visible)} onChange={e => onChange(rows.map((r,j) => i === j ? { ...r, visible: e.target.checked } : r))} />Show section</label>}<div className="flex gap-2"><button type="button" disabled={i === 0} className={button} onClick={() => { const copy = [...rows]; [copy[i-1],copy[i]] = [copy[i],copy[i-1]]; onChange(copy); }}>Move up</button><button type="button" className={button} onClick={() => onChange(rows.filter((_,j) => j !== i))}>Remove</button></div></div>)}</div><button type="button" className={`${button} mt-4`} onClick={() => onChange([...rows, { ...blank }])}>+ Add {title.toLowerCase().replace(/s$/, '')}</button></section>;
}
export default function IndiaAdmin() {
  const [pages, setPages] = useState<IndiaPage[]>([]);
  const [form, setForm] = useState<IndiaPage | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [preview, setPreview] = useState(false);
  const [dirty, setDirty] = useState(false);
  async function load() { setLoading(true); setError(''); try { setPages(await getIndiaAdminPages()); } catch (e) { setError(handleApiError(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!dirty) return; const guard = (e: BeforeUnloadEvent) => { e.preventDefault(); }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty]);
  function update<K extends keyof IndiaPage>(key: K, value: IndiaPage[K]) { setForm(p => p ? { ...p, [key]: value } : p); setDirty(true); setMessage(''); }
  function open(page: IndiaPage | null) { if (dirty && !window.confirm('Discard unsaved changes?')) return; setForm(page ? structuredClone(page) : null); setDirty(false); setPreview(false); setMessage(''); setError(''); }
  async function save(status: IndiaPage['status']) {
    if (!form || busy) return; setBusy(true); setError(''); setMessage('');
    try { const response = form._id ? await adminApi.put(`/india/admin/pages/${form._id}`, { ...form, status }) : await adminApi.post('/india/admin/pages', { ...form, status }); setForm(response.data.data); setDirty(false); setPages(await getIndiaAdminPages()); setMessage(status === 'published' ? 'Published. Website content is updated.' : 'Saved as draft. This page is not publicly visible.'); }
    catch (e) { setError(handleApiError(e)); } finally { setBusy(false); }
  }
  async function seed() { if (busy) return; setBusy(true); setError(''); try { const r = await adminApi.post('/india/admin/seed'); setPages(await getIndiaAdminPages()); setMessage(r.data.message); } catch(e) { setError(handleApiError(e)); } finally { setBusy(false); } }
  return <AdminLayout><div className="max-w-6xl space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">MBBS India</h1><p className="mt-1 text-sm text-gray-500">Manage your India overview, state guides and SEO.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/universities" className={button}>Manage colleges</Link>{form && <button className={button} onClick={() => open(null)}>Back to states</button>}</div></div>
    {error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}<button className="ml-3 underline" onClick={() => void load()}>Retry loading</button></div>}{message && <p role="status" className="rounded-xl bg-green-50 p-4 text-sm text-green-800">{message}</p>}
    {!form ? <><div className="flex flex-wrap gap-2"><button className={button} disabled={loading || busy} onClick={() => open(pages.find(p => p.kind === 'overview') || emptyIndiaPage('overview'))}>Edit India homepage</button><button className={`${button} !bg-[#F26419] !text-white`} disabled={loading || busy} onClick={() => open(emptyIndiaPage())}>+ Add state</button><button disabled={busy || loading} className={button} onClick={seed}>{busy ? 'Importing…' : 'Import 5 starter states'}</button></div><p className="text-xs text-gray-500">Starter import adds missing records only. Existing content is preserved. College mapping and India-specific fields are available in the existing college editor.</p>{loading ? <p role="status">Loading states…</p> : <div className="grid gap-4 md:grid-cols-2">{pages.map(p => <article key={p._id} className="rounded-xl border border-gray-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{p.kind === 'overview' ? 'India homepage' : p.name}</h2><span className={`rounded-full px-3 py-1 text-xs ${p.status === 'published' ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-800'}`}>{p.status}</span></div><p className="my-3 text-xs text-gray-500">{indiaPath(p)}</p><button className={button} onClick={() => open(p)}>Edit content & SEO</button>{p.status === 'published' && <Link href={indiaPath(p)} target="_blank" className="ml-4 text-sm text-[#F26419]">View page ↗</Link>}</article>)}{!pages.length && <p className="rounded-xl border border-dashed p-8 text-gray-500">Add a state or import the starter content to begin.</p>}</div>}</> : <form onSubmit={e => { e.preventDefault(); void save('published'); }} className="space-y-5">
      <div className="sticky top-0 z-20 flex flex-wrap items-center gap-2 rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><span className="mr-auto text-sm font-semibold">{form.name || 'New state'}{dirty ? ' · Unsaved changes' : ''}</span><button type="button" className={button} onClick={() => setPreview(p => !p)}>{preview ? 'Close preview' : 'Preview'}</button><button type="button" disabled={busy} className={button} onClick={() => void save('draft')}>{form.status === 'published' ? 'Unpublish & save draft' : 'Save draft'}</button><button disabled={busy} className={`${button} !bg-[#F26419] !text-white`}>{busy ? 'Saving…' : 'Publish'}</button></div>
      {preview ? <div className="overflow-hidden rounded-xl border border-gray-200"><p className="bg-amber-50 p-3 text-sm text-amber-800">Preview of unsaved content. Enquiries are disabled; college listings load on the public page.</p><IndiaPageView page={form} states={pages.filter(p => p.kind === 'state' && p.status === 'published')} preview /></div> : <>
      <section className="space-y-4 rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold">Page details</h2><div className="grid gap-4 sm:grid-cols-2"><TextField required label="Name" value={form.name} onChange={v => { update('name',v); if (!form._id && form.kind === 'state') update('slug', v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')); }} />{form.kind === 'state' && <TextField required label="URL slug" value={form.slug} onChange={v => update('slug',v)} />}</div><TextField required label="Page heading" value={form.title} onChange={v => update('title',v)} /><TextField required multiline label="Introduction" value={form.intro} onChange={v => update('intro',v)} /><div className="grid gap-4 sm:grid-cols-2"><TextField label="Academic year" value={form.academicYear} onChange={v => update('academicYear',v)} /><TextField type="date" label="Last reviewed" value={form.verifiedAt} onChange={v => update('verifiedAt',v)} /><TextField label="Counselling authority" value={form.authority} onChange={v => update('authority',v)} /><TextField type="url" label="Official counselling URL" value={form.officialUrl} onChange={v => update('officialUrl',v)} /><TextField label="Counselling button label" value={form.ctaLabel} onChange={v => update('ctaLabel',v)} /><TextField type="number" label="Display order" value={String(form.sortOrder)} onChange={v => update('sortOrder',Number(v))} /></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.featured} onChange={e => update('featured',e.target.checked)} />Featured state</label><ImageUploader folder="countries" currentImage={form.image} onUpload={v => update('image',v)} label="Page / state image" /><TextField label="Image URL" value={form.image} onChange={v => update('image',v)} /><TextField label="Image alt text" value={form.imageAlt} onChange={v => update('imageAlt',v)} /></section>
      <Rows title="Sections" rows={form.sections} onChange={v => update('sections',v)} blank={{title:'',body:'',visible:true}} fields={[{key:'title',label:'Heading'},{key:'body',label:'Content (plain text; new lines are preserved)',multiline:true}]} />
      <Rows title="Highlights" rows={form.highlights} onChange={v => update('highlights',v)} blank={{label:'',value:''}} fields={[{key:'label',label:'Label'},{key:'value',label:'Value (use verified figures only)'}]} />
      <Rows title="FAQs" rows={form.faqs} onChange={v => update('faqs',v)} blank={{question:'',answer:''}} fields={[{key:'question',label:'Question'},{key:'answer',label:'Answer',multiline:true}]} />
      <Rows title="Sources" rows={form.sources} onChange={v => update('sources',v)} blank={{label:'',url:''}} fields={[{key:'label',label:'Source name'},{key:'url',label:'Official source URL'}]} />
      <section className="space-y-4 rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold">SEO & sharing</h2><TextField required label={`Meta title (${form.seo.metaTitle.length} characters)`} value={form.seo.metaTitle} onChange={v => update('seo',{...form.seo,metaTitle:v})} /><TextField required multiline label={`Meta description (${form.seo.metaDescription.length} characters)`} value={form.seo.metaDescription} onChange={v => update('seo',{...form.seo,metaDescription:v})} /><TextField label="Canonical URL (leave blank for automatic)" value={form.seo.canonicalUrl} onChange={v => update('seo',{...form.seo,canonicalUrl:v})} /><ImageUploader folder="countries" label="Social sharing image" currentImage={form.seo.ogImage} onUpload={v => update('seo',{...form.seo,ogImage:v})} /><TextField type="url" label="Social image URL" value={form.seo.ogImage} onChange={v => update('seo',{...form.seo,ogImage:v})} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.seo.noindex} onChange={e => update('seo',{...form.seo,noindex:e.target.checked})} />Keep this page out of search results (noindex)</label><p className="text-xs text-gray-500">Published, indexable pages enter the sitemap automatically. Changing a saved slug creates a permanent redirect.</p></section></>}
    </form>}
  </div></AdminLayout>;
}
